Лабораторная работа № 1: **Numpy**<br>
Выполнил: **Стадников Александр, гр.6135**

In [1]:
import numpy as np

### Задание 1: 12 методов из документации NumPy
Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать из работу в блокноте. Демонстрация каждой функции в своей ячейке. Если снабдите комментарием что делает данная операция — будет вообще прекрасно.

1. np.array

Что делает: Инициализирует массив из данного массивоподобного массива, позволяет задать тип данных в массиве

In [2]:
a = np.array(object=range(1,11))
print(a)
a_float = np.array(object=range(1,11),dtype=np.float)
print(a_float)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


2. np.full

Что делает: инициализирует массив заданной формы, элементы которого равны fill_value

In [3]:
b = np.full(shape=(4,4),fill_value=2)
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


3. np.arrange

Что делает: создает массив из элементов на интервале [start,stop) c шагом step

In [4]:
c = np.arange(start=1,stop=3,step=0.25)
print(c)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75]


4. np.random.randn

Что делает: генерирует массив заданной формы с псевдослучайными числами распределенными по нормальному закону. Если размерности массива не заданы, то вернет одно число.

In [5]:
print(np.random.randn())
print(np.random.randn(2,5))

1.934827314579338
[[ 0.86944487 -0.72473515  0.4386185   0.36469085 -0.7983384 ]
 [-1.94869876 -1.08206722  1.01268007  0.37337292 -0.36643219]]


5. np.shape

Что делает: возвращает форму массив

In [6]:
print(np.shape(b))

(4, 4)


6. np.reshape

Что делает: меняет форму массива на предоставленную, новая форма должна быть совместима с предыдущей. Т.е. произведения размерностей должны быть равны.

In [7]:
d = np.reshape(a=b,newshape=(2,8))
print(d)
'Shape: {}'.format(d.shape)

[[2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2]]


'Shape: (2, 8)'

7. ndarray.T

Что делает: транспонирование массива

In [8]:
e= d.T
print(e)
'Shape: {}'.format(e.shape)

[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


'Shape: (8, 2)'

8. == и немножно [ ]

Что делает: сравнение массивов, сравнение элементов массива с числом

In [9]:
#Для примера возьмем массив а и возьмем остаток от деления на 3
tmp = a % 3
print('tmp      : {}'.format( tmp ))
#В результате сравнения на позициях, где элемент равен 0 в tmp,
#в результирующем массиве получим True
res = tmp == 0
print('tmp == 0 : {}'.format( res ))
#С помощью такого массива можем вытащить из массива а, все элементы кратные 3
print('a[res]   : {}'.format(a[res]))

tmp      : [1 2 0 1 2 0 1 2 0 1]
tmp == 0 : [False False  True False False  True False False  True False]
a[res]   : [3 6 9]


9. np.all

Что делает: если все элементы массива == True, то возвращет True, иначе False

In [10]:
print(np.all(res))
print(np.all([True, True, True]))
print(np.all([False,False,False]))

False
True
False


10. np.any

Что делает: True, если хотя бы один элемент массива == True, если ни одни элемент не == True, то False

In [11]:
print(np.any(res))
print(np.any([True, True, True]))
print(np.any([False,False,False]))

True
True
False


11. np.nansum

Что делает: Сумма элементов массива (по заданной оси), где Nan приравнивается к 0

In [12]:
a1 = np.array([[1,2,3],[4,np.nan,6],[np.nan,8,9]])
print(a1)
print(np.nansum(a1))
print(np.nansum(a1,axis=0))
print(np.nansum(a1,axis=1))

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [nan  8.  9.]]
33.0
[ 5. 10. 18.]
[ 6. 10. 17.]


12. np.floor

Что делает: округление вниз

In [13]:
print('c          : {}'.format(c))
print('np.floor(c): {}'.format(np.floor(c)))

c          : [1.   1.25 1.5  1.75 2.   2.25 2.5  2.75]
np.floor(c): [1. 1. 1. 1. 2. 2. 2. 2.]


### Задание 2: OLAP-куб
**Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам.** <br> <br>
Оси: 
- 0: ID группы товаров 
- 1: ID магазина 
- 2: день месяца, в котором осуществляются продажи (предположим у нас в OLAP-кубе собраны продажи за месяц). 

- Содержимое ячейки: продажи в тыс. рублей данной категории товаров в данном магазине в данный день.

In [14]:
products = np.arange(0, 22, 1)
shops = np.arange(0, 5, 1)
days = np.arange(1, 31, 1)
cube = np.zeros([products.size, shops.size, days.size])

for p in range(products.size):
  for s in range(shops.size):
    for d in range(days.size):
      cube[p, s, d] = np.random.randint(10, 80)

print(cube)

[[[61. 17. 48. ... 69. 21. 21.]
  [17. 61. 72. ... 33. 18. 42.]
  [21. 50. 53. ... 66. 18. 22.]
  [48. 23. 37. ... 24. 56. 72.]
  [38. 56. 68. ... 51. 63. 66.]]

 [[11. 24. 39. ... 24. 10. 49.]
  [63. 50. 12. ... 49. 41. 55.]
  [43. 74. 35. ... 29. 79. 61.]
  [35. 41. 41. ... 76. 22. 15.]
  [66. 70. 51. ... 30. 58. 56.]]

 [[11. 15. 33. ... 51. 50. 25.]
  [35. 62. 65. ... 14. 77. 35.]
  [21. 73. 73. ... 59. 33. 79.]
  [58. 51. 65. ... 28. 26. 75.]
  [55. 25. 22. ... 36. 38. 64.]]

 ...

 [[52. 42. 36. ... 20. 25. 61.]
  [52. 43. 37. ... 76. 38. 50.]
  [29. 60. 20. ... 77. 57. 41.]
  [62. 47. 67. ... 51. 22. 15.]
  [33. 33. 55. ... 30. 54. 16.]]

 [[75. 26. 17. ... 64. 35. 63.]
  [37. 40. 29. ... 72. 51. 39.]
  [11. 69. 56. ... 71. 73. 22.]
  [39. 63. 61. ... 11. 75. 78.]
  [57. 71. 60. ... 34. 23. 64.]]

 [[42. 19. 48. ... 71. 68. 59.]
  [48. 57. 69. ... 50. 33. 55.]
  [76. 79. 71. ... 64. 32. 52.]
  [45. 19. 16. ... 57. 45. 65.]
  [22. 70. 10. ... 67. 55. 53.]]]


### Задание 3: посчитать статистики для OLAP-куба.
Для получившегося OLAP-куба посчитать суммарные, средние, минимальные и максимальные продажи (на самом деле любые агрегатные функции можно использовать), зафиксировав значения по одной, двум или трём осям: например взять какой-то определённый набор товаров и набор городов или диапазон дней и сагрегировать данные по всем ячейкам из зафиксированного набора. Пример: получить сумму, среднее, минимум и максимум по продажам 10-20 чисел месяца для товаров [1,3,4] по всем городам (или по конкретному набору городов). Попробуйте различные варианты индексации и различные варианты срезов, насколько хватит фантазии.

In [15]:
print("Общая сумма продаж всех товаров во всех магазинах за весь месяц: \n")
print(np.sum(cube[:,:,:]))
print("\n-----------------------------------------------------\n")

print("Сумма по продажам 1-5 чисел месяца для товара 9 по всем магазинам: \n")
print(np.sum(cube[9,:,[days[0:5]]]))
print("\n-----------------------------------------------------\n")

print("Минимум по продажам 10-20 чисел месяца для товара 16 в магазине 3: \n")
print(np.min(cube[16,3,[days[9:20]]]))
print("\n-----------------------------------------------------\n")

print("Минимум по продажам 15-20 чисел месяца для товара 9 в магазине 2: \n")
print(np.min(cube[9,2,[days[14:20]]]))
print("\n-----------------------------------------------------\n")

print("Стандартное отклонение по продажам 1-10 чисел месяца для товара 1 по всем магазинам: \n")
print(np.std(cube[1,:,[days[0:10]]]))
print("\n-----------------------------------------------------\n")


print("Максимум по продажам за все время для товара 12 в магазине 2: \n")
print(np.max(cube[12,2,:]))
print("\n-----------------------------------------------------\n")

print("Cреднее по продажам за все время для товара 1 в магазине 1: \n")
print(np.mean(cube[1,1,:]))
print("\n-----------------------------------------------------\n")

Общая сумма продаж всех товаров во всех магазинах за весь месяц: 

147687.0

-----------------------------------------------------

Сумма по продажам 1-5 чисел месяца для товара 9 по всем магазинам: 

1012.0

-----------------------------------------------------

Минимум по продажам 10-20 чисел месяца для товара 16 в магазине 3: 

15.0

-----------------------------------------------------

Минимум по продажам 15-20 чисел месяца для товара 9 в магазине 2: 

39.0

-----------------------------------------------------

Стандартное отклонение по продажам 1-10 чисел месяца для товара 1 по всем магазинам: 

20.853623186391378

-----------------------------------------------------

Максимум по продажам за все время для товара 12 в магазине 2: 

77.0

-----------------------------------------------------

Cреднее по продажам за все время для товара 1 в магазине 1: 

46.833333333333336

-----------------------------------------------------

